version: "3.9"

services:
  #
  # Services
  #
  database:
    image: postgres
    networks:
      - server-local
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./container/database/scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
  server:
    image: rust
    networks:
      - network-1
      - server-local
    volumes:
      - cargo-target:/app/target
    init: true
    working_dir: /usr/src/myapp
    command: "/app/target/debug/server"

  #
  # Commands
  #
  build:
    image: rust
    volumes:
      - ./:/usr/src/myapp
      - cargo-registry:/usr/local/cargo/registry
      - cargo-target:/app/target
    working_dir: /usr/src/myapp
    command: "cargo build"
    environment:
      - CARGO_BUILD_TARGET_DIR=/app/target
    profiles:
      - command
  client:
    image: rust
    networks:
      - network-1
    volumes:
      - cargo-target:/app/target
      - user-local:/app/local
    depends_on:
      - server
    init: true
    working_dir: /usr/src/myapp
    command: "/app/target/debug/client"
    profiles:
      - command

volumes:
  cargo-registry:
  cargo-target:
  db-store:
  user-local:

networks:
  network-1:
  server-local:
